export const SITE = {
  name:      "Naviss Technologies",
  tagline:   "Where Location Meets Intelligence",
  sub:       "Geospatial & Digital Solutions · Abuja, Nigeria",
  phone:     "+234 806 696 8490",
  email:     "contact@naviss.tech",
  location:  "Abuja, Nigeria",
  founded:   "2025",
  social: [
    { label: "LinkedIn", href: "https://www.linkedin.com/company/naviss-technologies/" },
    { label: "Twitter / X", href: "https://twitter.com/navisstech" },
    { label: "GitHub", href: "https://github.com" },
    { label: "Instagram", href: "https://www.instagram.com/naviss.technologies?igsh=MWhpbXNndmxoaTFvOA%3D%3D&utm_source=qr" }
  ],
};

export const NAV = [
  { label: "Services", href: "/#services"  },
  { label: "Projects", href: "/projects"  },
  { label: "Team",     href: "/team"      },
  { label: "Careers",  href: "/careers"   },
  { label: "Contact",  href: "/contact"   },
];

export const PROJECTS = [
  {
    id: "001",
    title: "West Africa GeoPortal",
    client: "GMES-MIFMAS Programme / African Union Commission",
    region: "West Africa (Multi-Country)",
    year: "2024-2025",
    sector: "Regional Development",
    tags: ["Geospatial data", "Web GIS", "Open Data"],
    body: "Comprehensive geospatial data portal providing access to 56+ spatial datasets across 6 West African countries (Nigeria, Ghana, Mali, Benin, Burkina Faso, Côte d'Ivoire). Platform enables researchers, policymakers and development practitioners to explore, visualize, analyze and download geospatial data including rivers, settlements, infrastructure, land cover, and administrative boundaries.",
    impact: "56+ datasets · 6 countries · 1,000+ daily users · 50,000+ features mapped",
    image: "/docs.jpg",
    imageAlt: "Satellite view of West African coastline and terrain",
  },
  {
    id: "002",
    title: "AirSense Nigeria",
    client: "NASRDA (National Space Research & Development Agency)",
    region: "Nigeria (Multi-City)",
    year: "2024-2025",
    sector: "Environment & Public Health",
    tags: ["Real-Time", "AI/ML", "Satellite Data"],
    body: "Real-time air quality monitoring platform integrating satellite data with ground sensors across Nigeria's major cities (Abuja, Lagos, Port Harcourt, Kano). Provides actionable environmental intelligence to scientists, policymakers, and citizens through live AQI readings, historical trend analysis, predictive modeling, and health-impact assessments.",
    impact: "4 cities monitored · 24/7 real-time data · 99.8% uptime · <2min latency",
    image: "https://images.unsplash.com/photo-1537372023620-37161b1ad8ac?w=1400&q=85",
    imageAlt: "City skyline with atmospheric monitoring overlay",
  },
  {
    id: "003",
    title: "Surveyor General Information System (SGIS)",
    client: "Office of the Surveyor General, Kwara State (KW-GIS)",
    region: "Kwara State, Nigeria",
    year: "2025",
    sector: "Land Administration",
    tags: ["Land information system", "PostGIS", "Workflow Automation"],
    body: "Comprehensive land registration and survey workflow automation platform for the Office of the Surveyor General. Four-component system including WebGIS parcel database, land registration workflows, institutional email infrastructure, and capacity development programme. Deployed on private office server infrastructure.",
    impact: "Paper workflows eliminated · 4 departments unified · 60% faster processing",
    image: "https://images.unsplash.com/photo-1685266325930-ffe4937f6eb9?w=1400&q=85",
    imageAlt: "Surveyor using digital equipment in field",
  },
  {
    id: "004",
    title: "OGIM – Nigeria Oil & Gas Infrastructure Monitor",
    client: "Agricultural Development Agency",
    region: "Nigeria and Some part of West Africa",
    year: "2024",
    sector: "Oil & Gas",
    tags: ["Remote Sensing", "NDVI", "Dashboard"],
    body: "The Nigeria Oil & Gas Infrastructure Monitor (OGIM) is a comprehensive web-based geospatial intelligence platform designed to provide real-time visibility, spatial analysis, and strategic oversight of oil and gas infrastructure assets across Nigeria. OGIM transforms dispersed infrastructure data into a unified, interactive mapping system that enables operators, regulators, and stakeholders to monitor assets, analyze spatial relationships, and make informed decisions about Nigeria's energy sector.",
    impact: "200K+ ha monitored · 34% fewer field inspections · 6 LGAs served",
    image: "/ss.png",
    imageAlt: "Aerial view of green agricultural fields",
  },
{
  id: "005",
  title: "Kwara State Sustainable Development Monitor",
  client: "Office of the Surveyor General, Kwara State",
  region: "Ilorin, Kwara State",
  year: "2026",
  sector: "Government / Infrastructure",
  tags: ["GIS", "Infrastructure Monitoring", "Nigeria", "PostGIS", "geodatabase"],
  body: "GIS dashboard monitoring Health, Power, Water, and Road infrastructure across all 16 LGAs of Kwara State. Built on a PostGIS spatial database populated from GPS field surveys, with real-time status updates, heatmap and choropleth visualisation modes, polygon-based spatial filtering, and a mobile-responsive interface accessible to field officers on smartphones.",
  impact: "75 features mapped · 16 LGAs indexed · 4 infrastructure layers · Real-time monitoring",
  image: "/project2.png",
  imageAlt: "Aerial view of Ilorin city showing road networks and urban infrastructure",
},
  {
    id: "006",
    title: "IDP Displacement Tracker",
    client: "International NGO",
    region: "North-East Nigeria",
    year: "2024",
    sector: "Humanitarian",
    tags: ["Mobile Data", "Offline-First", "Real-Time"],
    body: "Offline-capable mobile data collection and case management for IDP registration across three states. Automatic sync ensures field teams operate on verified live data at all times even in areas with limited connectivity.",
    impact: "12,000+ registered · 3-state coverage · 40% faster intake",
    image: "https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?w=1400&q=85",
    imageAlt: "Field worker using tablet for data collection",
  },
];

export const SERVICES = [
  { n:"01", title:"Geospatial Strategy & Solution Design",    tags:["Feasibility","ROI Analysis","Roadmaps"],       body:"Needs assessment, solution architecture, business case development, and digital transformation roadmaps — built around your organisation's goals." },
  { n:"02", title:"Data Collection, Management & Integration",tags:["Drone Mapping","Cloud Infra","ETL"],           body:"Field collection via mobile, drone and satellite. Spatial database design, AWS / Azure / GCP cloud infrastructure, API development." },
  { n:"03", title:"Custom Software & Intelligent Systems",    tags:["AI/ML","Web GIS","Real-Time"],                 body:"Web GIS dashboards, mobile apps, AI/ML analytics, automated alerts, and real-time spatial visualisation — built around your workflows." },
  { n:"04", title:"Implementation & Technical Support",       tags:["Deployment","UAT","Helpdesk"],                 body:"Deployment, UAT, performance optimisation, documentation, helpdesk support, and long-term maintenance." },
  { n:"05", title:"Training & Capacity Development",          tags:["Workshops","Certification","Mentorship"],      body:"Customised training from beginner to advanced, train-the-trainer workshops, certification programs, and ongoing mentorship." },
];

export const PROCESS = [
  { n:"01", time:"1–2 wks",  title:"Discovery",       body:"Deep-dive needs assessment, stakeholder interviews, feasibility analysis. Align on goals, constraints, and what real success looks like." },
  { n:"02", time:"2–4 wks",  title:"Solution Design", body:"Architecture, technology selection, business case, data strategy, and a phased roadmap tailored for your context — not a template." },
  { n:"03", time:"4–12 wks", title:"Build & Deploy",  body:"Agile sprints, regular demos, rigorous UAT, clean deployment with full documentation. No black boxes, no disappearing acts." },
  { n:"04", time:"Ongoing",  title:"Train & Sustain", body:"Your team fully owns the system. Comprehensive training, documentation, and genuine long-term partnership." },
];

export const SECTORS = [
  { title:"Agriculture & Natural Resources", sub:"Precision farming, land management, forestry" },
  { title:"Urban Planning & Development",    sub:"City planning, infrastructure, smart cities"  },
  { title:"Public Health",                   sub:"Disease surveillance, facility mapping"       },
  { title:"Humanitarian & Development",      sub:"Disaster response, IDP services, monitoring"  },
  { title:"Environment & Conservation",      sub:"Biodiversity, climate adaptation"             },
  { title:"Energy & Utilities",              sub:"Asset management, network planning"           },
  { title:"Transportation & Logistics",      sub:"Route optimisation, fleet, infrastructure"    },
  { title:"Finance & Investment",            sub:"Market analysis, site selection, risk mapping"},
  { title:"Oil and Gas",                     sub:"Exploration, pipeline monitoring, environmental impact" },
];


export const TEAM = [
  {
    id: "001",
    name: "Ismail Muzammil",
    role: "co-Founder & Principal Consultant",
    shortBio: "Geospatial strategist with 8+ years transforming spatial data into strategic advantage for governments and enterprises across West Africa.",
    bio: "Ismail founded Naviss Technologies with a vision to democratize access to geospatial intelligence across Africa. With extensive experience in large-scale GIS implementations for government agencies, NGOs, and private sector clients, he leads strategic direction and client engagement. His expertise spans WebGIS architecture, land administration systems, and capacity development programmes.",
    expertise: ["Geospatial Strategy", "GIS Architecture", "PostGIS / PostgreSQL", "Python / Django", "AWS / Azure", "Spatial APIs"],
    image: "/myimage.png",
    email: "ismailmuzammil206@gmail.com",
    linkedin: "https://linkedin.com/in/adeolaadeyemi",
  },
  {
    id: "002",
    name: "Surv Dahir Muazu Omar",
    role: "Co-Founder & Director of Geospatial Strategy",
    shortBio: "A SURCON-registered surveyor and academic at the University of Ilorin, Dahir integrates 15+ years of experience in Land, Hydrographic, and Oil & Gas surveying with modern geospatial AI to drive operational excellence.",
    bio: "Dahir is a spatial data strategist who bridges the gap between traditional surveying and computational intelligence. A SURCON-registered professional and Lecturer at the University of Ilorin, his recent work focuses on Machine Learning applications for flood mapping and Cloud Computing (Google Earth Engine) for environmental monitoring. With a Master’s from the University of Lagos, Dahir leads our operations by turning multi-petabyte satellite datasets into precise, actionable field intelligences.",
    expertise: ["Geospatial Strategy", "Land Administration", "GIS Architecture", "Client Engagement"],
    image: "/omar.jpeg",
    email: "dahirmomar@gmail.com",
    linkedin: "https://www.linkedin.com/in/dahir-muazu-omar-mnis-58160a4b",
  },
  {
    id: "003",
    name: "Ibrahim Habeeb Damilola",
    role: "Senior Remote Sensing Analyst",
    shortBio: "Remote sensing specialist with deep expertise in satellite imagery analysis, drone mapping, and environmental monitoring.",
    bio: "Ibrahim leads Naviss's remote sensing and earth observation initiatives. He has processed and analyzed satellite imagery across millions of hectares for agricultural monitoring, land cover mapping, and environmental assessment. His technical proficiency spans multispectral analysis, change detection, and automated feature extraction using machine learning.",
    expertise: ["Satellite Imagery Analysis", "Drone Mapping & Photogrammetry", "Google Earth Engine", "QGIS / ArcGIS Pro", "Machine Learning for RS"],
    image: "/habib.jpg?w=800&q=85",
    email: "habeebibrahim946@gmail.com",
    linkedin: "https://linkedin.com/in/ibrahimmusa",
  },
  {
    id: "004",
    name: "Mahmud Abdulsalam",
    role: "Chief Operating Officer & Co-Founder",
    shortBio: " Abdulsalam is a Geospatial Expert and Co-Founder with over 5 years of experience driving precision in the surveying and geoinformatics industry.  ",
    bio: "Mahmud brings a unique blend of field expertise and operational leadership to Naviss. With a background in surveying and geoinformatics, he has extensive experience in land surveying, hydrography, and geospatial operations within the oil and gas industry. As COO, Mahmud oversees Naviss's operational strategy, ensuring that our technical solutions are not only innovative but also scalable and sustainable for long-term growth.",
    expertise: ["Data Collection", "UAV Operations", "GNSS / Survey Equipment", "Team Coordination", "Quality Assurance"],
    image: "https://images.unsplash.com/photo-1776942010620-ebd77b749e22?q=80&w=687&",
    email: "habeebibrahim946@gmail.com",
    linkedin: "https://linkedin.com/in/fatimabello",
  },
  {
    id: "005",
    name: "Adebayo Oluwatosin Francis",
    role: "Geospatial Analyst",
    shortBio: "A proactive and solution-driven professional with hands-on experience in geospatial data collection, analysis, and mapping operations",
    bio: "Adebayo manages Naviss's field operations, coordinating data collection teams, training enumerators, and ensuring quality assurance across projects. His experience spans mobile data collection campaigns in remote areas, UAV operations, and GNSS surveys. He bridges the gap between field realities and technical requirements.",
    expertise: ["Data Collection", "QGIS", "Data Processing", "Cartography", "Python Scripting", "Spatial Analysis"],
    image: "/tosin.jpeg?w=800&q=85",
    email: "emeka@naviss.tech",
    linkedin: "https://linkedin.com/in/emekanwankwo",
  },
  {
    id: "006",
    name: "AYODELE SAMSON FERANMI",
    role: "GIS Analyst & Remote Sensing Specialist",
    shortBio: "Samson Feranmi is a geospatial analyst and urban planner with specializing in spatial analysis and enviromental assessment",
    bio: "Samson Feranmi is a geospatial analyst specializing in spatial analysis and environmental assessment.He has experience in geospatial data analysis, remote sensing, mapping, and urban planning, with a focus on applying GIS techniques to real-world environmental and urban challenges.",
    expertise: ["Urban Planning", "Google earth engine", "", "Geospatial analysis", "Technical Documentation"],
    image: "/fera.png",
    email: "Sferanmi29@gmail.com",
    linkedin: "www.linkedin.com/in/samson-ayodele-932b6432b",
  },
  //   {
  //   id: "006",
  //   name: "AYODELE SAMSON FERANMI",
  //   role: "Training & Capacity Development Lead",
  //   shortBio: "",
  //   bio: "Samson Feranmi is a geospatial analyst specializing in spatial analysis and environmental assessment.He has experience in geospatial data analysis, remote sensing, mapping, and urban planning, with a focus on applying GIS techniques to real-world environmental and urban challenges.",
  //   expertise: ["GIS Training Curriculum", "Capacity Building", "Workshop Facilitation", "Technical Documentation", "Mentorship"],
  //   image: "https://images.unsplash.com/photo-155183622-d5d88e9218df?w=800&q=85",
  //   email: "ngozi@naviss.tech",
  //   linkedin: "https://linkedin.com/in/ngoziokeke",
  // },
  {
    id: "007",
    name: "Yusuf Abubakar",
    role: "Junior GIS Analyst",
    shortBio: "Emerging geospatial professional supporting data processing, spatial analysis, and quality assurance across projects.",
    bio: "Yusuf supports Naviss projects through data processing, cartographic production, and spatial analysis tasks. He is developing expertise in QGIS, Python scripting, and geodatabase management while contributing to live client deliverables. His attention to detail and eagerness to learn make him a valuable asset to the technical team.",
    expertise: ["QGIS", "Data Processing", "Cartography", "Python Scripting", "Spatial Analysis"],
    image: "https://images.unsplash.com/photo-1776942010620-ebd77b749e22?q=80&w=687&",
    email: "yusuf@naviss.tech",
    linkedin: "https://linkedin.com/in/yusufabubakar",
  },
];
// export const TICKER = ["Geospatial Intelligence","Drone & Satellite Mapping","Custom GIS Platforms","AI / ML Spatial Analytics","Digital Transformation","Cloud Infrastructure","Capacity Development","Real-Time Monitoring","Web GIS Dashboards","Spatial Databases"];

export const CAREERS = [
  {
    id: "001",
    title: "Senior GIS Developer",
    location: "Abuja, Nigeria",
    type: "Full-Time",
    department: "Engineering",
    posted: "2025-04-15",
    description: "We're looking for a senior full-stack GIS developer to architect and build next-generation spatial platforms for government and enterprise clients across West Africa.",
    responsibilities: [
      "Design and implement WebGIS applications using Next.js, React, and PostGIS",
      "Build scalable spatial APIs and data processing pipelines",
      "Lead technical architecture decisions for multi-tenant geospatial platforms",
      "Mentor junior developers and conduct code reviews",
      "Collaborate with clients to translate requirements into technical solutions",
      "Optimize spatial queries and database performance",
    ],
    requirements: [
      "5+ years of professional software development experience",
      "Strong proficiency in JavaScript/TypeScript and modern web frameworks (React, Next.js, Vue)",
      "Deep experience with PostGIS/PostgreSQL and spatial databases",
      "Solid understanding of GIS concepts, coordinate systems, and spatial data formats",
      "Experience building RESTful APIs and working with cloud infrastructure (AWS/Azure)",
      "Excellent problem-solving skills and attention to detail",
      "Strong communication skills and ability to work with non-technical stakeholders",
    ],
    niceToHave: [
      "Experience with Leaflet, Mapbox, or OpenLayers",
      "Knowledge of Python for geospatial data processing",
      "Familiarity with CI/CD pipelines and DevOps practices",
      "Previous work on government or NGO projects",
      "Contributions to open-source geospatial projects",
    ],
  },
  {
    id: "002",
    title: "Remote Sensing Analyst",
    location: "Abuja, Nigeria",
    type: "Full-Time",
    department: "Technical",
    posted: "2025-04-10",
    description: "Join our remote sensing team to analyze satellite imagery and drone data for agricultural monitoring, environmental assessment, and land use mapping projects across Nigeria.",
    responsibilities: [
      "Process and analyze multispectral and SAR satellite imagery",
      "Conduct land cover classification and change detection analysis",
      "Develop automated workflows for large-scale image processing",
      "Plan and execute UAV mapping missions for project sites",
      "Create technical reports and cartographic outputs for client deliverables",
      "Train clients and field teams on remote sensing workflows",
    ],
    requirements: [
      "Bachelor's degree in Geography, Remote Sensing, Environmental Science, or related field",
      "3+ years of experience in satellite image analysis and interpretation",
      "Proficiency with QGIS or ArcGIS Pro",
      "Experience with Google Earth Engine or similar cloud-based platforms",
      "Strong knowledge of spectral indices (NDVI, EVI, NDWI, etc.)",
      "Ability to work independently and manage multiple projects",
      "Excellent written and verbal communication skills",
    ],
    niceToHave: [
      "UAV pilot certification and field mapping experience",
      "Python scripting for geospatial analysis",
      "Machine learning for image classification",
      "Experience with Sentinel, Landsat, or Planet imagery",
      "Field data collection experience in Nigeria or West Africa",
    ],
  },
  {
    id: "003",
    title: "GIS Trainer / Capacity Development Specialist",
    location: "Abuja, Nigeria",
    type: "Full-Time",
    department: "Training",
    posted: "2025-04-05",
    description: "Design and deliver comprehensive GIS training programmes for government agencies, NGOs, and corporate clients. Help build institutional capacity across West Africa.",
    responsibilities: [
      "Develop training curricula for beginner to advanced GIS topics",
      "Deliver hands-on workshops and certification programmes",
      "Create training materials, documentation, and video tutorials",
      "Conduct needs assessments and design customized training solutions",
      "Provide ongoing mentorship and technical support to trainees",
      "Evaluate training effectiveness and continuously improve content",
    ],
    requirements: [
      "Bachelor's degree in GIS, Geography, Education, or related field",
      "4+ years of experience in GIS and spatial analysis",
      "2+ years of experience in training or teaching (formal or informal)",
      "Strong proficiency in QGIS and/or ArcGIS",
      "Excellent presentation and communication skills",
      "Ability to explain complex technical concepts to non-technical audiences",
      "Patience, empathy, and genuine passion for teaching",
    ],
    niceToHave: [
      "Formal teaching qualification or certification",
      "Experience designing e-learning content",
      "Knowledge of adult learning principles",
      "Experience training government or NGO staff",
      "Proficiency in multiple Nigerian languages",
    ],
  },
];

export const TICKER = [
  "Geospatial Intelligence",
  "Drone & Satellite Mapping",
  "Custom GIS Platforms",
  "AI / ML Spatial Analytics",
  "Digital Transformation",
  "Cloud Infrastructure",
  "Capacity Development",
  "Real-Time Monitoring",
  "Web GIS Dashboards",
  "Spatial Databases"
];
 
// Categorization helpers
export const PROJECT_SECTORS = [
  "All",
  "Regional Development",
  "Environment & Public Health",
  "Land Administration",
  "Agriculture",
  "Urban Planning",
  "Humanitarian",
] as const;
 
export const PROJECT_STATUS = [
  "All",
  "Live",
  "In Development",
  "Completed",
] as const;
 